### ISSUE TITLE
Doesn't work with 7.3.0

### ISSUE THREAD

**Issue by smcpoland** [Bonitasoft-Community/expense-report-example#2]
Doesn't work with 7.3.0

In fact will not even import.

regards

**Comment by FunTomAS74** [comment]
I just tested it with Bonita BPM 7.5.4 and the import worked.
Importing the bos file you need to overwrite all conflicts.
Just the "Create Expense Report" page looks different , I don't have a total sum and i can't deleate rows ...
Everything else works fine ....

![image](https://user-images.githubusercontent.com/29210815/29185408-6b5855f8-7e09-11e7-8d8c-83097442f3ee.png)

**Comment by besserer** [comment]
> Acabo de probarlo con Bonita BPM 7.5.4 y la importación funcionó. 
> Importando el archivo bos necesitas sobrescribir todos los conflictos. 
> Solo la página "Crear informe de gastos" se ve diferente, no tengo una suma total y no puedo borrar filas ... 
> Todo lo demás funciona bien ...
> 
> ![imagen](https://user-images.githubusercontent.com/29210815/29185408-6b5855f8-7e09-11e7-8d8c-83097442f3ee.png)

lograste sumar los valores ??

**Comment by amottier** [comment]
The example has been updated and is now only compatible with Bonita 7.9.4. Please open a new issue in case you having trouble to run the example with Bonita 7.9.4.
