### ISSUE TITLE
Bonita BPM 7.5.4 is working but ...

### ISSUE THREAD

**Issue by FunTomAS74** [Bonitasoft-Community/expense-report-example#3]
for the Create Expense Report I don't see the total sum and the Button to remove a Line is not working ...

![expense report _ 2017-08-10 20_14_13-bonita bpm portal](https://user-images.githubusercontent.com/29210815/29186021-7ca3fec8-7e0b-11e7-8ab3-a3231b149397.png)

**Comment by FunTomAS74** [comment]
by the way ... on the community ( https://community.bonitasoft.com/project/expense-report-example1 ) site under "Downloads" there is only the old Version 3.0 bos file linked , not the new Version 4.0

**Comment by besserer** [comment]
Amigos en la imagen sale que suma los valores y en el vídeo no lo hace, e intentado hacerlo pero no puedo me pueden ayudar a sumar los valores que ingresan múltiples



Friends in the image comes out that adds the values ​​and in the video does not do it, and tried to do it but I can not can help me to add the values ​​that enter multiple

**Comment by besserer** [comment]
> por cierto ... en el sitio de la comunidad ( https://community.bonitasoft.com/project/expense-report-example1 ) en "Descargas" solo existe el archivo antiguo bos de la versión 3.0 vinculado, no la nueva versión 4.0

lograste sumar ???

**Comment by amottier** [comment]
- In the latest version of the example the total sum has been removed. It might be back in a future update.
- Button to remove a line should now be functional.
- On community website a new release for the project has been added.
