### ISSUE TITLE
Import fails with 7.6.2

### ISSUE THREAD

**Issue by sashank** [Bonitasoft-Community/expense-report-example#4]
Importing of the .bos file version 5.0 fails when imported in 7.6.2 community edition of Bonita Studio. 
It says version incompatible

**Comment by omarma** [comment]
Hello,
I have the same issue in 7.8.1.
Any solution ?

**Comment by bv74** [comment]
Hello, 
same thing in 7.8.0 with the message  : designed with a subscription edition. Incompatible with community edition. 
Any solution ?

**Comment by thtuanTr** [comment]
anybody have solution please ?

**Comment by ghost** [comment]
same issue here with 7.8.4...

importing seems to work fine, when I re-import my project, created with the community edition:

![Screenshot from 2019-06-14 17-31-31](https://user-images.githubusercontent.com/25619972/59520558-89ec1800-8eca-11e9-8954-0cb2e7aac2ab.png)


but then I downloaded the expense report example from the community doc site:

![Screenshot from 2019-06-14 17-31-49](https://user-images.githubusercontent.com/25619972/59520653-ba33b680-8eca-11e9-8815-c5777dbc9189.png)


and tried to import the file I just finished downloading:

![Screenshot from 2019-06-14 17-31-57](https://user-images.githubusercontent.com/25619972/59520742-e94a2800-8eca-11e9-8b63-ff79bfcf7eab.png)


but it failed...

![Screenshot from 2019-06-14 17-32-02](https://user-images.githubusercontent.com/25619972/59520757-eea77280-8eca-11e9-9e04-baa3c7008f1f.png)

**Comment by amottier** [comment]
Hi,

Sorry about this issue. Example was accidentally build for the Enterprise Edition. Latest version created for Bonita 7.9.4 is compatible again with the Community Edition.
